[package]
name = "pbkdf2"
version = "0.4.0-pre"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Generic implementation of PBKDF2"
documentation = "https://docs.rs/pbkdf2"
repository = "https://github.com/RustCrypto/password-hashing"
keywords = ["crypto", "password", "hashing"]
categories = ["cryptography", "no-std"]
edition = "2018"

[dependencies]
crypto-mac = "0.8.0-pre"
byteorder = { version = "1", default-features = false }

rayon = { version = "1", optional = true }
base64 = { version = "0.9", optional = true }
rand = { version = "0.7", optional = true }
hmac = { version = "0.8", optional = true }
sha2 = { version = "0.9", optional = true }
subtle = { version = "2", default-features = false , optional = true }

[dev-dependencies]
hmac = "0.8"
sha-1 = "0.9"
sha2 = "0.9"

[features]
default = ["include_simple"]
parallel = ["rayon"]
include_simple = ["sha2", "hmac", "rand", "base64", "subtle"]

[badges]
travis-ci = { repository = "RustCrypto/password-hashing" }
