language: rust
rust:
  - stable
  - nightly
matrix:
  include:
    script: cd scrypt; cargo test --verbose --no-default-features
  allow_failures:
    - rust: nightly
script: cargo test --verbose --all
